# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'Traber' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Traber
    
    pod 'Material'
    pod 'YYCategories'
    pod 'SDWebImage'
    pod 'MBProgressHUD'
    pod 'IQKeyboardManagerSwift'
    pod 'AFNetworking'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'ShareSDK3'
    pod 'MOBFoundation'
    pod 'ShareSDK3/ShareSDKPlatforms/Facebook'
    pod 'Stripe'
    
end
